<a href="https://colab.research.google.com/github/Lokasurya66/surya24/blob/master/DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 1.a Find minimum among three nunbers

In [ ]:
 
a=int(input("Enter the first number "))
b=int(input("Enter the second number "))
c=int(input("Enter the third number "))
if a<b:
    if b<c:
        print(a," is the minimum number")
    else:
        print(c," is the minimum number")
else:
    if b<c:
        print(b," is the minimum number")
    else:
        print(c," is the minimum number")

Enter the first number 6
Enter the second number 9
Enter the third number 3
3  is the minimum number


1.b Find the GCD and LCM of two/three numbers

In [ ]:
 
a=int(input("Enter the first number "))
b=int(input("Enter the second number "))
i=1
while (i <= a and i <= b):
  if(a%i == 0 and b%i == 0):
    gcd = i
  i = i + 1
lcm = (a*b)/gcd
print("GCD of the given numbers is ", gcd)
print("LCM of the given numbers is ",lcm)

Enter the first number 20
Enter the second number 30
GCD of the given numbers is  10
LCM of the given numbers is  60.0


 1.c.check whether the given number is perfect

In [ ]:
 
n=int(input("enter any number:"))
sum=0
for i in range(1,n):
    if(n%i==0):
       sum=sum+i
if(sum==n):
    print("the number",sum," is a perfect number")
else:
    print("the number is not a perfect number")

enter any number:8
the number is not a perfect number


1.c Print twin primes upto a specified limit

In [ ]:
 
def prime(n):
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
 
def twin_prime(start, end):
    for i in range(start, end):
        j= i + 2
        if (prime(i) and prime(j)):
            print ("{:d} and {:d}".format(i, j))
 
twin_prime(2, 250)

3 and 5
5 and 7
11 and 13
17 and 19
29 and 31
41 and 43
59 and 61
71 and 73
101 and 103
107 and 109
137 and 139
149 and 151
179 and 181
191 and 193
197 and 199
227 and 229
239 and 241


 1.d print twin primes upto specified limit

In [ ]:
 
n1 = int(input("Enter the first number "))
n2 = int(input("Enter the last number "))
 
for n in range(n1, n2+1):  
    if n > 1:
        for i in range(2,n):
            if (n % i == 0):
                break  
        else:  
            print(n)

Enter the first number 2
Enter the last number 220
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211


 1.f find the sum of digits of a number.check whether given number is armstrong number or not

In [ ]:
 
import math 
n1 = int(input("Enter your first number "))
n2 = int(input("Enter your second number "))
print("The armstrong numbers form the interval are ")
if n1 < n2:
    for i in range(n1,n2+1):
        sum = 0
        temp = i
        
        while temp != 0:
            last = temp%10
            sum = sum + math.pow(last,3)
            temp = temp//10
        if sum==i:
            print(i)

Enter your first number 2
Enter your second number 60
The armstrong numbers form the interval are 


 1.g swap of two numbers

In [ ]:
 
a=int(input("enter number:"))
b=int(input("enter number:"))
print("before swap the values of a and b are:",a,b)
a,b=b,a
print("after swap the values of a and b are:",a,b)

enter number:5
enter number:10
before swap the values of a and b are: 5 10
after swap the values of a and b are: 10 5


1.h Perform all the five arithmetic operations

In [ ]:
 
a= 10
b = 30
c = 10
 
c = a + b
print ("Addition - Value of c is ", c)
 
c = a - b
print ("Subtraction - Value of c is ", c)
 
c = a * b
print ("Multiplication - Value of c is ", c)
 
c = a / b
print ("Division - Value of c is ", c)
 
c = a % b
print ("Modulus - Value of c is ", c)

Addition - Value of c is  40
Subtraction - Value of c is  -20
Multiplication - Value of c is  300
Division - Value of c is  0.3333333333333333
Modulus - Value of c is  10


 2.a.copy the contents from one array to another array

In [ ]:
 
import numpy as np
x = np.array([24, 27, 30, 29, 18, 14])
print("Original array:")
print(x)
y = np.empty_like (x)
y[:] = x
print("\nCopy of the said array:")
print(y)

Original array:
[24 27 30 29 18 14]

Copy of the said array:
[24 27 30 29 18 14]


 2.b Copy the contents from one array to another in reverse order

In [ ]:
 
import array as arr
source = arr.array('i', [10, 20, 30, 40])
dest = arr.array('i', [])
 
for index in range(0, len(source)):
    dest.insert(index, source[index])
    
for i in dest:
    print(i, end=" ")
print(type(dest))
print("The reverse of the array: ")
for i in range(len(source)-1, -1, -1):
    dest.insert(index, source[index])
    print(dest[i], end=" ")

10 20 30 40 <class 'array.array'>
The reverse of the array: 
40 30 20 10 

 2.c.delete the duplicate elements from an array

In [ ]:
 
import array as arr
def delete_duplicate(array1):
    array2 = arr.array("i", [])
    for num in array1: 
        if num not in array2: 
            array2.append(num) 
    print("\nArray after deleting the duplicate elements is:")
    for i in array2:
        print(i, end = ", ")
 
delete_duplicate(arr.array('i', [1,2,4,5,2,3,7,3,8,2,9]))


Array after deleting the duplicate elements is:
1, 2, 4, 5, 3, 7, 8, 9, 

 3.a Representing sparse matrix

In [ ]:
 
import numpy as np 
from scipy.sparse import csr_matrix 
  
# Creating a 3 * 4 sparse matrix 
sparseMatrix = csr_matrix((3, 4),  
                          dtype = np.int8).toarray() 
  
# Print the sparse matrix 
print(sparseMatrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


 3.b.sparse matrix addition

In [ ]:
 
m1=[[1,0,3],
     [0,5,6],
     [7,0,0]]
m2=[[0,5,1],
    [0,0,8],
    [0,2,6]]     
result=[[0,0,0],
    [0,0,0],
    [0,0,0]] 
for i in range(len(m1)):
  for j in range(len(m2)):
    for k in range(len(m2)):
      result[i][j] = m1[i][j]+m2[i][j]
print("The resultant matrix ")
for r in result:
  print(r)

The resultant matrix 
[1, 5, 4]
[0, 5, 14]
[7, 2, 6]


 3.c sprase matrix transpose

In [ ]:
 
N=4
def transpose(A,B): 
  
    for i in range(N): 
        for j in range(N): 
            B[i][j] = A[j][i] 
 
A = [ [1, 1, 1, 1], 
    [2, 2, 2, 2], 
    [3, 3, 3, 3], 
    [4, 4, 4, 4]] 
   
   
B = A[:][:] 
  
transpose(A, B) 
   
print("Result matrix is") 
for i in range(N): 
    for j in range(N): 
        print(B[i][j], " ", end='') 
    print()

Result matrix is
1  2  3  4  
2  2  3  4  
3  3  3  4  
4  4  4  4  


 4.Write a program to perform Linear Search and Binary Search on a list stored in an array

In [ ]:
 
def linear(alist,key):
  for i in range(len(alist)):
    if alist[i]==key :
      return i 
  return -1
 
 
alist = input('Enter the list of numbers :')
alist = alist.split()
alist =[int(x) for x in alist]
key = int(input('The number to search for :'))
 
index = linear(alist,key)
if index<0 :
   print('{} was not found '.format(key))
else:
  print('{} was found at index {}.'.format(key,index))

Enter the list of numbers :5
The number to search for :5
5 was found at index 0.


 5.a insert a node at beginning at ending and at a given position

In [ ]:
 
class node:
    def _init_(self,dval,nval):
        self.dval=dval
        self.nval=nval
class slist:
    def _init_(self):
        self.head=None
        self.tail=None
        self.size=0
    def len(self):
        return self.size
    def isempty(self):
        return self.size==0
    def addlast(self,e):
        new=node(e,None)
        if self.isempty():
            self.head=new
        else:
            self.tail.nval=new
        self.tail=new
        self.size+=1
    def display(self):
        p=self.head
        while p:
            print(p.dval,end='--')
            p=p.nval
        print(' ')
    def removefirst(self):
        if self.isempty():
            print('empty list')
            return
        print('element deleted form the list is',self.head.dval)
        self.head=self.head.nval
        self.size-=1
        if self.isempty():
            self.tail=None
            return
    def removelast(self):
        if self.isempty():
            print('empty list')
            return
        temp=self.head
        i=1
        while i<self.len()-1:
            temp=temp.nval
            i+=1
        self.tail=temp
        temp=temp.nval
        x=temp.nval
        self.tail.nval=None
        self.size-=1
        return x
    def count(self):
        i=0
        p=self.head
        while p:
            p=p.nval
            i+=1
            return i
    def search(self,el):
        p=self.head
        i=0
        while (i<(self.len())):
            print(p.dval)
            if p.dval==el:
                print('element is found')
                return
            p=p.nval
            i+=1
        print('element is not found')

 6.doble linked list

In [ ]:
 
class Node:
    def init(self,preval,dataval,nextval):
        self.dataval=dataval
        self.nextval=nextval
        self.preval=preval
class dlist:
    def init(self):
        self.head=None
        self.tail=None
        self.size=0
    def len(self):
        return self.size
    def isempty(self):
        return self.size==0
    def addlast(self,ele):
        new=Node(None,ele,None)
        if self.isempty():
            self.head=new
            self.tail=new
        else:
            self.tail.nextval=new
            new.preval=self.tail
            self.tail=new
        self.size+=1
    def display(self):
        temp=self.head
        while (temp):
            print(temp.dataval,end='--')
            temp=temp.nextval
    def removelast(self):
        if self.isempty():
            print('empty list')
            return
        print('deleted element is :',self.tail.dataval)
        self.tail.preval.nextval=None
        self.tail=self.tail.preval
        self.size-=1
    def removefirst(self):
        if self.isempty():
            print('empty list')
            return
        else:
            print('deleted element is :',self.head.dataval)
            self.head.nextval=self.head
            self.head.preval=None
            self.size-=1
            return
    def search(self,ele):
        temp=self.head
        i=0
        while(temp):
            print('yes')
            if temp.dataval==ele:
                print('element found')
                return
            i+=1
            temp=temp.nextval

7.circular linked list

In [ ]:
 
class Node:
    def init(self,preval,dataval,nextval):
        self.dataval=dataval
        self.nextval=nextval
        self.preval=preval
class dlist:
    def init(self):
        self.head=None
        self.tail=None
        self.size=0
    def len(self):
        return self.size
    def isempty(self):
        return self.size==0
    def addlast(self,ele):
        new=Node(None,ele,None)
        if self.isempty():
            self.head=new
            self.tail=new
        else:
            self.tail.nextval=new
            new.preval=self.tail
            self.tail=new
        self.size+=1
    def display(self):
        temp=self.head
        while (temp):
            print(temp.dataval,end='--')
            temp=temp.nextval
    def removelast(self):
        if self.isempty():
            print('empty list')
            return
        print('deleted element is :',self.tail.dataval)
        self.tail.preval.nextval=None
        self.tail=self.tail.preval
        self.size-=1
    def removefirst(self):
        if self.isempty():
            print('empty list')
            return
        else:
            print('deleted element is :',self.head.dataval)
            self.head.nextval=self.head
            self.head.preval=None
            self.size-=1
            return
    def search(self,ele):
        temp=self.head
        i=0
        while(temp):
            print('yes')
            if temp.dataval==ele:
                print('element found')
                return
            i+=1
            temp=temp.nextval

 8.write a program to create a stack and perform various operation on it

In [ ]:
 
class Stack:
    def _init_(self):
        self.items = []
 
    def is_empty(self):
        return self.items == []
 
    def push(self, data):
        self.items.append(data)
 
    def pop(self):
        return self.items.pop()
 
 
s = Stack()
while True:
    print('push <value>')
    print('pop')
    print('quit')
    do = input('perform operation').split()
 
    operation = do[0].strip().lower()
    if operation == 'push':
        s.push(int(do[1]))
    elif operation == 'pop':
        if s.is_empty():
            print('Stack is empty.')
        else:
            print('Popped value: ', s.pop())
    elif operation == 'quit':
        break

push <value>
pop
quit


 9.convert the influx expression into postfix form

In [ ]:
 
class infix_to_postfix:
    precedence={'^':5,'*':4,'/':4,'+':3,'-':3,'(':2,')':1}
    def _init_(self):
        self.items=[]
        self.size=-1
    def push(self,value):
        self.items.append(value)
        self.size+=1
    def pop(self):
        if self.isempty():
            return 0
        else:
            self.size-=1
            return self.items.pop()
    def isempty(self):
        if(self.size==-1):
            return True
        else:
            return False
    def seek(self):
        if self.isempty():
            return false
        else:
            return self.items[self.size]
    def isOperand(self,i):
        if i in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ':
            return True
        else:
            return False
    def infixtopostfix (self,expr):
        postfix=""
        print('postfix expression after every iteration is:')
        for i in expr:
            if(len(expr)%2==0):
                print("Incorrect infix expr")
                return False
            elif(self.isOperand(i)):
                postfix +=i
            elif(i in '+-*/^'):
                while(len(self.items)and self.precedence[i]<=self.precedence[self.seek()]):
                    postfix+=self.pop()
                self.push(i)
            elif i is '(':
                self.push(i)
            elif i is ')':
                o=self.pop()
                while o!='(':
                    postfix +=o
                    o=self.pop()
            print(postfix)
                #end of for
        while len(self.items):
            if(self.seek()=='('):
                self.pop()
            else:
                postfix+=self.pop()
        return postfix
s=infix_to_postfix()
expr=input('enter the expression ')
result=s.infixtopostfix(expr)
if (result!=False):
    print("the postfix expr of :",expr,"is",result)

 10.create a queue and perform various operations on it

In [ ]:
 
class Node:
    def _init_(self, element, next):
        self.element = element
        self.next = next
 
class QueuesLinked:
    def _init_(self):
        self.front = None
        self.rear = None
        self.size = 0
 
    def _len_(self):
        return self.size
 
    def isempty(self):
        return self.size == 0
 
    def enqueue(self, e):
        newest = Node(e, None)
        if self.isempty():
            self.front = newest
        else:
            self.rear.next = newest
        self.rear = newest
        self.size += 1
 
    def dequeue(self):
        if self.isempty():
            print('Queue is empty')
            return
        e = self.front.element
        self.front = self.front.next
        self.size -= 1
        if self.isempty():
            self.rear = None
        return e
 
    def first(self):
        if self.isempty():
            print('Queue is empty')
            return
        return self.front.element
 
    def display(self):
        p = self.front
        while p:
            print(p.element,end=' <-- ')
            p = p.next
        print()
 
 
Q = QueuesLinked()
Q.enqueue(5)
Q.enqueue(3)
print('Queue:')
Q.display()
print('Queue Length:', len(Q))
ele = Q.dequeue()
print('Queue:')
Q.display()
print('Queue Length:', len(Q))
print('Removed Element:',ele)
print('Is Queue Empty:',Q.isempty())
Q.enqueue(7)
print('Queue:')
Q.display()
print('Queue Length:', len(Q))
Q.enqueue(12)
print('Queue:')
Q.display()
print('Queue Length:', len(Q))
ele = Q.dequeue()
print('Queue:')
Q.display()
print('Queue Length:', len(Q))
print('Removed Element:',ele)
print('First Element:',Q.first())

 11.Write a program to create a binary tree and perform various traversals

In [ ]:
 
def __init__(self,data):
        self.left = None
        self.right = None
        self.data = data 
 
#To insert a new node
    def insert(self,child,direction):
        if direction == "right":
            self.right = child 
        elif direction == "left":
            self.left = child 
 
#To print the tree (LRN method - Left Node,Right Node,Root Node)
    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        if self.right:
            self.right.PrintTree()
        print(self.data)
 
#Use the insert method to add nodes 
A = Node("A")
B = Node("B")
C = Node("C")
D = Node("D")
E = Node("E")
F = Node("F")
A.insert(B,"left")
B.insert(C,"right")
C.insert(D,"left")
A.insert(E,"right")
E.insert(F,"right")
A.PrintTree()

 12.create a binary search tree and perform some operations

In [ ]:
 
class BST():
  def __init__(self,data):
    self.data=data
    self.left=None
    self.right=None

  
  def addchild(self,data):
    if data==self.data:
      return
    
    if data<self.data:
      if self.left:
        self.left.addchild(data)
      else:
        self.left=BST(data)

    else:
      if self.right:
        self.right.addchild(data)
      else:
        self.right=BST(data)

 
  def inorder(self):
    elements=[]
    if self.left:
      elements+=self.left.inorder()
    if self.data:
      elements.append(self.data)
    if self.right:
      elements+=self.right.inorder()
    return elements

 
  def preorder(self):
    elements=[]
    if self.data:
      elements.append(self.data)
    if self.left:
      elements+=self.left.inorder()
    if self.right:
      elements+=self.right.inorder()
    return elements

  
  def postorder(self):
    elements=[]
    if self.left:
      elements+=self.left.inorder()
    if self.right:
      elements+=self.right.inorder()
    if self.data:
      elements.append(self.data)
    return elements

    
  def search(self,val):
    if val==self.data:
      return True
    if val<self.data:
      if self.left:
        val=self.left.search(val)
      else:
        return False
    else: 
      if self.right: 
        val=self.right.search(val)
      else:
        return False
    return val

def build_tree(elements):
  root=BST(elements[0])
  for i in range(1,len(elements)):
    root.addchild(elements[i])
  return root

if _name=="main_":
  numbers=[17, 4, 1, 20, 9, 23, 18, 34]
  numbers_tree=build_tree(numbers)
  print(numbers_tree.inorder())
  print(numbers_tree.preorder())
  print(numbers_tree.postorder())
  
  print(numbers_tree.search(4))
  print(numbers_tree.search(10)